### ISSUE TITLE
Error while building on Windows (8.1)

### ISSUE THREAD

**Issue by kengey** [playcanvas/developer.playcanvas.com#44]
TypeError: Cannot read property 'legacy' of undefined

**Comment by willeastcott** [comment]
Confirmed. Full output:

```
C:\dev\playcanvas\developer.playcanvas.com>npm install
npm WARN deprecated metalsmith-templates@0.7.0: This package was split into two simpler plugins: metalsmith-layouts and metalsmith-in-place
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated lodash.createcallback@2.4.4: This package is discontinued. Use lodash.iteratee@^4.0.0.
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated node-uuid@1.4.7: use uuid module instead

C:\dev\playcanvas\developer.playcanvas.com>node build.js
Failed to load: C:\dev\playcanvas\developer.playcanvas.com\lib\i18n..\content\ja\messages.json
Failed to load: C:\dev\playcanvas\developer.playcanvas.com\lib\i18n..\content\ru\messages.json
Failed to load: C:\dev\playcanvas\developer.playcanvas.com\lib\i18n..\content\zh\messages.json
done
TypeError: Cannot read property 'legacy' of undefined
    at C:\dev\playcanvas\developer.playcanvas.com\lib\contents-json\index.js:191:60
    at Array.forEach (native)
    at Ware.<anonymous> (C:\dev\playcanvas\developer.playcanvas.com\lib\contents-json\index.js:65:19)
    at Ware.<anonymous> (C:\dev\playcanvas\developer.playcanvas.com\node_modules\wrap-fn\index.js:45:19)
    at Immediate.next (C:\dev\playcanvas\developer.playcanvas.com\node_modules\ware\lib\index.js:85:20)
    at Immediate.<anonymous> (C:\dev\playcanvas\developer.playcanvas.com\node_modules\wrap-fn\index.js:121:18)
    at runCallback (timers.js:637:20)
    at tryOnImmediate (timers.js:610:5)
    at processImmediate [as _immediateCallback] (timers.js:582:5)

C:\dev\playcanvas\developer.playcanvas.com>
```
